#!/usr/bin/env python3
"""The four SQL files, in the order they have to run, as one paste.

    python tools/sql.py setup.sql

Then open setup.sql, select all, and run it once in the Supabase SQL editor.
The four files are already safe to run twice, so this is too.

With no filename it writes to stdout instead, as UTF-8 bytes — not through
whatever encoding the console happens to have, because `python tools/sql.py >
setup.sql` on a Windows terminal writes cp1252 otherwise, and the em dashes in
the comments come out as bytes Postgres will not read.

They can also be run one at a time — supabase/README.md does it that way, and
that is the better way to read what each one does. This exists because the
order matters and getting it wrong is a confusing afternoon: policies.sql
grants to is_admin(), which functions.sql defines, which needs the tables in
schema.sql to be there first.

Nothing is generated or rewritten here. The files are printed exactly as they
are on disk, so there is no second copy of the schema to drift out of date.
"""
import os
import sys

ORDER = ('schema.sql', 'functions.sql', 'policies.sql', 'seed.sql')
HERE = os.path.dirname(os.path.abspath(__file__))
SQL = os.path.join(os.path.dirname(HERE), 'supabase')


def bundle():
    out = ['-- Cognix — supabase/%s, in order, as one script.' % ', '.join(ORDER),
           '-- Generated by tools/sql.py. Safe to run more than once.']
    for name in ORDER:
        path = os.path.join(SQL, name)
        with open(path, 'r', encoding='utf-8') as fh:
            body = fh.read()
        out.append('\n\n-- %s\n-- %s\n-- %s\n'
                   % ('=' * 68, name, '=' * 68))
        out.append(body.rstrip())
    return '\n'.join(out) + '\n'


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    missing = [n for n in ORDER if not os.path.isfile(os.path.join(SQL, n))]
    if missing:
        sys.stderr.write('missing: %s\n' % ', '.join(missing))
        return 1
    raw = bundle().encode('utf-8')
    if argv and not argv[0].startswith('-'):
        with open(argv[0], 'wb') as fh:
            fh.write(raw)
        sys.stderr.write('%s — %d lines, %d files, UTF-8\n'
                         % (argv[0], raw.count(b'\n'), len(ORDER)))
        return 0
    sys.stdout.buffer.write(raw)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
